config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: 'rooms#index'
  resources :rooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  with_options presence: true do
  validates :title
  validates :description
  end 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @rooms = Room.all
  end

  def new
    @rooms = Room.new
  end

  def create
    @rooms = Room.new(rooms_params)
     if @rooms.save
      redirect_to root_path
     else
      render :new
     end
  end

  def show
    @rooms = Room.find(params[:id])
  end

  def destroy
    room = Room.find(params[:id])
    if room.destroy
      redirect_to root_path
    else
      render :show
    end
  end
  
  private
  def rooms_params
    params.require(:room).permit(:title, :description).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/index.html.erb
<div class="top-header">
<%=render partial: "shared/header", local:{user: @user}%>
</div>
<div class= "main">
<%=render partial: "shared/main_content", local:{room: @rooms}%>
</div>
<div class= "footer">
<%=render  "shared/footer"%>
</div>

app/views/rooms/new.html.erb
<div class= "whole-new-page">
 <%= form_with model:@rooms, local: true do |f|%>
  <div class="form">
    <div class="form-title">
    <%=f.label :title, "タイトル", class: "f-title"%>
    <%=f.text_field :title, class: "f-field"%>
    </div>
    <div class="form-text">
    <%=f.label :description, "説明", class:"f-text"%>
    <%=f.text_area :description, class: "f-area"%>
    </div>
    <div class="btn">
    <%=f.submit "送信", class: "submit-btn"%>
  </div>
  <% end %>
</div>

app/views/rooms/show.html.erb
<%= render "shared/header"%>
<div class="show-wrap">
<div class="del-btn">
<%=link_to "ルームを削除する", room_path, method: :delete%>
</div>
<div class="show-title">
<%= @rooms.title%>
</div>

<ol>
<li>
<details>
<summary>よろしく</summary>
<p>うまいぜ</p>
</details>
</li>
</ol>


</div>

app/views/shared/_error_message.html.erb
<% if user.errors.any? %>
<div class="error-alert">
  <ul>
    <% user.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
footer

app/views/shared/_header.html.erb
<div class="head-elements">
  <div class= "head-title">
    <div class="title">
    <h1><%=link_to "Tasks", root_path %></h1>
    </div>
  </div>
  <div class="create-room">
  <%= link_to "部屋を作る", new_room_path %>
  </div>
  <div class="log-in-top">
  <ul class="log-in-list">
  <%if user_signed_in?%>
   <li><%=link_to "#{current_user.name}", "#"%></li>
   <li><%=link_to "ログアウト", destroy_user_session_path, method: :delete%></li>
   <%else%>
   <li><%= link_to "ログイン", new_user_session_path%></li>
   <li><%= link_to "新規登録", new_user_registration_path %></li>
   <%end%>
  </ul>
  </div>
</div>

app/views/shared/_main_content.html.erb
<div class= main>
  <div class= "task-list">
    <% @rooms.reverse_each do |room|%>
    <ul class= "ul-list">
    <li>
          <div class="box29">
              <div class="box-title"><%=link_to room.title, room_path(room.id)%></div>
              <p><%=room.description%></p>
          </div>
     </li>
    </ul>
    <% end %>
  </div>
</div>